"""
Django settings for ormuco1 project.

Generated by 'AwsDemo-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qu&#y3s0!i^y=2od55o(u6q^@d7ojw2))$d(m3^$_8(-%=zy1@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'AwsDemo.contrib.admin',
    'AwsDemo.contrib.auth',
    'AwsDemo.contrib.contenttypes',
    'AwsDemo.contrib.sessions',
    'AwsDemo.contrib.messages',
    'AwsDemo.contrib.staticfiles',
    'ormuco1',
]

MIDDLEWARE = [
    'AwsDemo.middleware.security.SecurityMiddleware',
    'AwsDemo.contrib.sessions.middleware.SessionMiddleware',
    'AwsDemo.middleware.common.CommonMiddleware',
    'AwsDemo.middleware.csrf.CsrfViewMiddleware',
    'AwsDemo.contrib.auth.middleware.AuthenticationMiddleware',
    'AwsDemo.contrib.messages.middleware.MessageMiddleware',
    'AwsDemo.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ormuco1.urls'

TEMPLATES = [
    {
        'BACKEND': 'AwsDemo.template.backends.AwsDemo.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'AwsDemo.template.context_processors.debug',
                'AwsDemo.template.context_processors.request',
                'AwsDemo.contrib.auth.context_processors.auth',
                'AwsDemo.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ormuco1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'AwsDemo.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'AwsDemo.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'AwsDemo.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'AwsDemo.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'AwsDemo.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
