---
- name: Copy configuration files
  hosts: all
  gather_facts: no

  tasks:
    - name: gunicorn error logs
      template: src=../config/gunicorn.err.log dest=/var/log/gunicorn
    - name: gunicorn output logs
      template: src=../config/gunicorn.out.log dest=/var/log/gunicorn
    - name: supervisor config file
      template: src=../config/gunicorn.conf dest=/etc/supervisor/conf.d/
      register: supervisor_config
    - name: supervisor restart
      shell: supervisorctl reread
    - name: supervisor update
      shell: supervisorctl update
    - name: nginx config file
      template: src=../config/django.conf dest=/etc/nginx/sites-enabled/
      register: nginx_config
    - name: nginx restart
      service: name=nginx state=restarted
      when: nginx_config.changed

