---
- hosts: all
  become: yes
  become_user: prajshet
  gather_facts: no

- hosts: all
  become: yes
  become_user: prajshet
  gather_facts: no
  environment:
    STATIC_ROOT: "{{ static_dir }}"

  tasks:
  - name: create static_root dir
    file: path={{ static_dir }} state=directory mode=0777
  - name: django migrate
    shell: python manage.py migrate --noinput chdir={{ repo_dir }}


- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
  - name: supervisor restart
    shell: supervisorctl reread
  - name: supervisor update
    shell: supervisorctl update
  - name: nginx test service
    shell: nginx -t

- hosts: all
  gather_facts: no
  tasks:
  - name: nginx restart
    service: name=nginx state=restarted

